depth = ..

INI_FILES = $(LY_FILES)
EXTRA_DIST_FILES = $(SCM_FILES)

INSTALLATION_DIR=$(local_lilypond_datadir)/ly
INSTALLATION_FILES=$(INI_FILES)

STEPMAKE_TEMPLATES = ly install

include $(depth)/stepmake/stepmake.make
