depth = ..

NAME = flower
MODULE_NAME = flower

README_FILES = NEWS-1.0 NEWS-1.1.46 README TODO
STEPMAKE_TEMPLATES = lilypond library c++ po test

# test uses LILYPOND_DATADIR
TEST_MODULE_LIBS = ../flower
export top-src-dir
include $(depth)/stepmake/stepmake.make
